wandb_version: 1

optimzier:
  desc: null
  value: adam
model:
  desc: null
  value: wgan_gp
_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.15.8
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1692810649.337452
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.11.3
      5: 0.15.8
      8:
      - 1
      - 5
